### ISSUE TITLE
Centered in window

### ISSUE THREAD

**Issue by afaur** [Extrawurst/unecht#1]
I got your project to build over the weekend and was able to run this on a Macbook Retina as well as another mac that isn't. (I took my libglfw.3.dylib along with the compiled program on a jump drive to run on the other machine.)  

I noticed that on the Macbook Pro Retina, the image that your drawing with OpenGL is in the bottom left hand corner, but when I ran it on my other mac the image was centered in the screen.  I don't currently have a screenshot of the one where it's centered but just wanted to mention this as I wasn't sure if this was intentional or not.

(ScreenShots are from Macbook Pro Retina)
![screen shot 2015-03-21 at 2 23 48 pm](https://cloud.githubusercontent.com/assets/898523/6788381/14cd6af8-d167-11e4-885e-ceeae5ffb94d.png)

![screen shot 2015-03-23 at 2 12 46 pm](https://cloud.githubusercontent.com/assets/898523/6788389/1f7ee45e-d167-11e4-9c6d-1dafb27e31d3.png)

**Comment by extrawurst** [comment]
oh thanks for your interest in my project. please note that this is under heavy development and in no ways stable or usable or anything ;)

I was not aware that anybody is toying around with it.

regarding glfw: yes this is not supplied by the project it must be installed on the running system.

regarding retina: that is an interesting finding. i will look into it.

**Comment by extrawurst** [comment]
since the glfw dependency is a matter of documentation and documentation is non existant to this point i consider this fixed. please drop me a line how you got interested in this project, will you?
